title: Stackbit Exto Theme
baseurl: /
permalink: '/:title/'
color_scheme: light
accent_color: pink
header:
  title: STRAPON U
  has_nav: true
footer:
  content: '&copy; STRAPONU.com All rights reserved.'
  links:
    - text: Strapon Shop on line
      url: 'https://straponu.com'
      new_window: true
  has_social: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
collections:
  posts:
    permalink: '/posts/:title/'
